In [1]:
!pip install -q sentence-transformers scikit-learn pandas numpy joblib

In [2]:
import pandas as pd
import numpy as np
import joblib

from sentence_transformers import SentenceTransformer
from sklearn.metrics.pairwise import cosine_similarity

print("CareerLens AI Training Environment Ready!")

CareerLens AI Training Environment Ready!

In [3]:
career_data = [

    {
        "role": "AI ML Engineer",
        "skills": """
        Python Machine Learning Deep Learning
        Scikit-learn TensorFlow PyTorch Pandas NumPy
        Artificial Intelligence NLP Computer Vision
        Model Training Model Deployment FastAPI
        """
    },

    {
        "role": "Data Scientist",
        "skills": """
        Python Machine Learning Statistics Probability
        Pandas NumPy Scikit-learn SQL Data Analysis
        Data Visualization Predictive Modeling
        Feature Engineering
        """
    },

    {
        "role": "Data Analyst",
        "skills": """
        SQL Excel Python Pandas Power BI Tableau
        Statistics Data Analysis Data Visualization
        Reporting Business Intelligence
        """
    },

    {
        "role": "Python Developer",
        "skills": """
        Python Object Oriented Programming
        Django Flask FastAPI REST API SQL
        Git Backend Development Testing
        """
    },

    {
        "role": "Backend Developer",
        "skills": """
        Python Java Node.js FastAPI Django Express
        REST API SQL MongoDB PostgreSQL
        Authentication Docker Backend Development
        """
    },

    {
        "role": "Full Stack Developer",
        "skills": """
        HTML CSS JavaScript React Node.js Express
        MongoDB SQL REST API Git
        Frontend Development Backend Development
        """
    },

    {
        "role": "Software Engineer",
        "skills": """
        Java Python C++ Data Structures Algorithms
        Object Oriented Programming Git SQL
        Software Engineering System Design Testing
        """
    },

    {
        "role": "DevOps Engineer",
        "skills": """
        Docker Kubernetes Jenkins GitHub Actions
        Linux AWS CI CD Terraform Automation
        Monitoring Cloud Deployment
        """
    },

    {
        "role": "Cloud Engineer",
        "skills": """
        AWS Azure Google Cloud Docker Kubernetes
        Linux Networking Cloud Computing
        Terraform Security Deployment
        """
    },

    {
        "role": "Cybersecurity Analyst",
        "skills": """
        Cybersecurity Network Security Linux Python
        Ethical Hacking Penetration Testing
        Firewalls Vulnerability Assessment
        Security Analysis SIEM
        """
    },

    {
        "role": "Generative AI Engineer",
        "skills": """
        Python Generative AI Large Language Models
        LLM Prompt Engineering RAG LangChain
        Vector Databases Embeddings Transformers
        FastAPI OpenAI Gemini Ollama
        """
    },

    {
        "role": "NLP Engineer",
        "skills": """
        Python Natural Language Processing NLP
        Transformers BERT Hugging Face
        Machine Learning Deep Learning
        Text Classification Embeddings
        """
    },

    {
        "role": "Computer Vision Engineer",
        "skills": """
        Python Computer Vision OpenCV YOLO
        Deep Learning CNN TensorFlow PyTorch
        Object Detection Image Processing
        """
    },

    {
        "role": "MLOps Engineer",
        "skills": """
        Python Machine Learning Docker Kubernetes
        MLflow CI CD AWS Model Deployment
        Model Monitoring FastAPI Git
        """
    },

    {
        "role": "Database Developer",
        "skills": """
        SQL MySQL PostgreSQL Oracle MongoDB
        Database Design Query Optimization
        Stored Procedures Data Modeling
        """
    }
]

career_df = pd.DataFrame(career_data)

print("Dataset shape:", career_df.shape)

career_df

Dataset shape: (15, 2)

,role,skills
0,AI ML Engineer,\n Python Machine Learning Deep Learnin...
1,Data Scientist,\n Python Machine Learning Statistics P...
2,Data Analyst,\n SQL Excel Python Pandas Power BI Tab...
3,Python Developer,\n Python Object Oriented Programming\n...
4,Backend Developer,\n Python Java Node.js FastAPI Django E...
5,Full Stack Developer,\n HTML CSS JavaScript React Node.js Ex...
6,Software Engineer,\n Java Python C++ Data Structures Algo...
7,DevOps Engineer,\n Docker Kubernetes Jenkins GitHub Act...
8,Cloud Engineer,\n AWS Azure Google Cloud Docker Kubern...
9,Cybersecurity Analyst,\n Cybersecurity Network Security Linux...
10,Generative AI Engineer,\n Python Generative AI Large Language ...
11,NLP Engineer,\n Python Natural Language Processing N...
12,Computer Vision Engineer,\n Python Computer Vision OpenCV YOLO\n...
13,MLOps Engineer,\n Python Machine Learning Docker Kuber...
14,Database Developer,\n SQL MySQL PostgreSQL Oracle MongoDB\...

In [4]:
def clean_text(text):

    text = str(text).lower()

    text = " ".join(
        text.split()
    )

    return text


career_df["clean_skills"] = (
    career_df["skills"]
    .apply(clean_text)
)

career_df[
    ["role", "clean_skills"]
].head()

                role                                       clean_skills
0     AI ML Engineer  python machine learning deep learning scikit-l...
1     Data Scientist  python machine learning statistics probability...
2       Data Analyst  sql excel python pandas power bi tableau stati...
3   Python Developer  python object oriented programming django flas...
4  Backend Developer  python java node.js fastapi django express res...

In [5]:
model = SentenceTransformer(
    "all-MiniLM-L6-v2"
)

print("NLP model loaded successfully!")

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/10.5k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/612 [00:00<?, ?B/s]

model.safetensors: reconstructing file:   0%|          |  0.00B / 90.9MB

model.safetensors: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

tokenizer_config.json:   0%|          | 0.00/350 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

NLP model loaded successfully!

In [6]:
career_embeddings = model.encode(
    career_df["clean_skills"].tolist(),
    normalize_embeddings=True,
    show_progress_bar=True
)

print(
    "Embeddings shape:",
    career_embeddings.shape
)

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Embeddings shape: (15, 384)

In [7]:
def predict_career(
    candidate_skills,
    top_n=5
):

    candidate_text = clean_text(
        candidate_skills
    )

    candidate_embedding = model.encode(
        [candidate_text],
        normalize_embeddings=True
    )

    similarities = cosine_similarity(
        candidate_embedding,
        career_embeddings
    )[0]

    results = career_df[
        ["role", "skills"]
    ].copy()

    results["match_score"] = (
        similarities * 100
    )

    results = results.sort_values(
        "match_score",
        ascending=False
    )

    return results.head(top_n)

In [8]:
candidate_skills = """

Python
Machine Learning
Scikit-learn
Pandas
NumPy
Artificial Intelligence
FastAPI
Generative AI
Gemini
Ollama
LLM

"""

results = predict_career(
    candidate_skills
)

results[
    ["role", "match_score"]
]

                        role  match_score
0             AI ML Engineer    64.388885
10    Generative AI Engineer    55.111736
1             Data Scientist    50.746555
12  Computer Vision Engineer    36.825066
11              NLP Engineer    32.109554

In [9]:
test_skills = """

HTML
CSS
JavaScript
React
Node.js
Express
MongoDB

"""

predict_career(
    test_skills
)[
    ["role", "match_score"]
]

                    role  match_score
5   Full Stack Developer    87.516068
4      Backend Developer    35.066544
14    Database Developer    25.788626
3       Python Developer     8.011793
7        DevOps Engineer     6.174503

In [10]:
test_skills = """

Docker
Kubernetes
AWS
Linux
Jenkins
Terraform
CI CD

"""

predict_career(
    test_skills
)[
    ["role", "match_score"]
]

                    role  match_score
7        DevOps Engineer    88.332382
8         Cloud Engineer    69.736656
13        MLOps Engineer    61.941063
4      Backend Developer    24.216944
5   Full Stack Developer    14.522648

In [11]:
def get_missing_skills(
    candidate_skills,
    target_role
):

    role_data = career_df[
        career_df["role"] == target_role
    ]

    if role_data.empty:
        return []

    required_text = (
        role_data.iloc[0]["skills"]
        .replace("\n", " ")
    )

    candidate_lower = (
        candidate_skills.lower()
    )

    required_skills = [
        skill.strip()
        for skill in required_text.split()
        if len(skill.strip()) > 2
    ]

    missing = []

    for skill in required_skills:

        if skill.lower() not in candidate_lower:

            if skill not in missing:
                missing.append(skill)

    return missing[:10]

In [12]:
get_missing_skills(
    candidate_skills,
    "AI ML Engineer"
)

['Deep',
 'TensorFlow',
 'PyTorch',
 'NLP',
 'Computer',
 'Vision',
 'Model',
 'Training',
 'Deployment']

In [13]:
joblib.dump(
    career_df,
    "career_profiles.pkl"
)

joblib.dump(
    career_embeddings,
    "career_embeddings.pkl"
)

print(
    "CareerLens model artifacts saved!"
)

CareerLens model artifacts saved!

In [14]:
import os

print(
    os.path.getsize(
        "career_profiles.pkl"
    )
)

print(
    os.path.getsize(
        "career_embeddings.pkl"
    )
)

5815
23281

In [15]:
skill_taxonomy = {

    "AI ML Engineer": [
        "Python",
        "Machine Learning",
        "Deep Learning",
        "Scikit-learn",
        "TensorFlow",
        "PyTorch",
        "Pandas",
        "NumPy",
        "Artificial Intelligence",
        "NLP",
        "Computer Vision",
        "Model Training",
        "Model Deployment",
        "FastAPI"
    ],

    "Data Scientist": [
        "Python",
        "Machine Learning",
        "Statistics",
        "Probability",
        "Pandas",
        "NumPy",
        "Scikit-learn",
        "SQL",
        "Data Analysis",
        "Data Visualization",
        "Predictive Modeling",
        "Feature Engineering"
    ],

    "Generative AI Engineer": [
        "Python",
        "Generative AI",
        "Large Language Models",
        "Prompt Engineering",
        "RAG",
        "LangChain",
        "Vector Databases",
        "Embeddings",
        "Transformers",
        "FastAPI",
        "OpenAI",
        "Gemini",
        "Ollama"
    ]
}


def get_missing_skills(candidate_skills, target_role):

    required_skills = skill_taxonomy.get(
        target_role,
        []
    )

    candidate_lower = candidate_skills.lower()

    missing = [
        skill
        for skill in required_skills
        if skill.lower() not in candidate_lower
    ]

    return missing

In [16]:
candidate_skills = """
Python
Machine Learning
Scikit-learn
Pandas
NumPy
Artificial Intelligence
FastAPI
Generative AI
Gemini
Ollama
LLM
"""

get_missing_skills(
    candidate_skills,
    "AI ML Engineer"
)

['Deep Learning',
 'TensorFlow',
 'PyTorch',
 'NLP',
 'Computer Vision',
 'Model Training',
 'Model Deployment']

In [17]:
import random
import pandas as pd

random.seed(42)

career_skill_map = {

    "AI ML Engineer": [
        "Python", "Machine Learning", "Deep Learning",
        "Scikit-learn", "TensorFlow", "PyTorch",
        "Pandas", "NumPy", "Artificial Intelligence",
        "NLP", "Computer Vision", "Model Deployment"
    ],

    "Data Scientist": [
        "Python", "Machine Learning", "Statistics",
        "Probability", "Pandas", "NumPy",
        "SQL", "Scikit-learn", "Data Visualization",
        "Feature Engineering", "Predictive Modeling"
    ],

    "Data Analyst": [
        "SQL", "Excel", "Python", "Pandas",
        "Power BI", "Tableau", "Statistics",
        "Data Analysis", "Data Visualization",
        "Business Intelligence"
    ],

    "Generative AI Engineer": [
        "Python", "Generative AI", "LLM",
        "Prompt Engineering", "RAG", "LangChain",
        "Vector Databases", "Embeddings",
        "Transformers", "Gemini", "OpenAI",
        "Ollama", "FastAPI"
    ],

    "NLP Engineer": [
        "Python", "NLP", "Transformers",
        "BERT", "Hugging Face", "Machine Learning",
        "Deep Learning", "Text Classification",
        "Embeddings", "PyTorch"
    ],

    "Computer Vision Engineer": [
        "Python", "Computer Vision", "OpenCV",
        "YOLO", "CNN", "Deep Learning",
        "TensorFlow", "PyTorch", "Object Detection",
        "Image Processing"
    ],

    "Python Developer": [
        "Python", "OOP", "Django", "Flask",
        "FastAPI", "REST API", "SQL",
        "Git", "Testing", "Backend Development"
    ],

    "Backend Developer": [
        "Python", "Java", "Node.js", "FastAPI",
        "Django", "Express", "REST API",
        "PostgreSQL", "MongoDB", "Docker",
        "Authentication"
    ],

    "Full Stack Developer": [
        "HTML", "CSS", "JavaScript", "React",
        "Node.js", "Express", "MongoDB",
        "SQL", "REST API", "Git"
    ],

    "Software Engineer": [
        "Java", "Python", "C++",
        "Data Structures", "Algorithms", "OOP",
        "Git", "SQL", "System Design",
        "Software Engineering", "Testing"
    ],

    "DevOps Engineer": [
        "Docker", "Kubernetes", "Jenkins",
        "GitHub Actions", "Linux", "AWS",
        "CI CD", "Terraform", "Automation",
        "Monitoring"
    ],

    "Cloud Engineer": [
        "AWS", "Azure", "Google Cloud",
        "Docker", "Kubernetes", "Linux",
        "Networking", "Terraform",
        "Cloud Computing", "Cloud Security"
    ],

    "MLOps Engineer": [
        "Python", "Machine Learning", "Docker",
        "Kubernetes", "MLflow", "CI CD",
        "AWS", "Model Deployment",
        "Model Monitoring", "FastAPI"
    ],

    "Cybersecurity Analyst": [
        "Cybersecurity", "Network Security",
        "Linux", "Python", "Ethical Hacking",
        "Penetration Testing", "Firewalls",
        "Vulnerability Assessment", "SIEM"
    ],

    "Database Developer": [
        "SQL", "MySQL", "PostgreSQL",
        "Oracle", "MongoDB", "Database Design",
        "Query Optimization", "Stored Procedures",
        "Data Modeling"
    ]
}

training_rows = []

# Generate 80 varied examples per career
for role, skills in career_skill_map.items():

    for _ in range(80):

        # Randomly select 60%-100% of role skills
        min_skills = max(4, int(len(skills) * 0.6))

        selected = random.sample(
            skills,
            random.randint(min_skills, len(skills))
        )

        random.shuffle(selected)

        training_rows.append({
            "text": " ".join(selected),
            "role": role
        })

career_training_df = pd.DataFrame(training_rows)

# Shuffle dataset
career_training_df = career_training_df.sample(
    frac=1,
    random_state=42
).reset_index(drop=True)

print("Dataset shape:", career_training_df.shape)
print()
print(career_training_df["role"].value_counts())

career_training_df.head()

Dataset shape: (1200, 2)

role
Database Developer          80
DevOps Engineer             80
Data Scientist              80
Computer Vision Engineer    80
AI ML Engineer              80
NLP Engineer                80
MLOps Engineer              80
Generative AI Engineer      80
Data Analyst                80
Python Developer            80
Software Engineer           80
Backend Developer           80
Full Stack Developer        80
Cloud Engineer              80
Cybersecurity Analyst       80
Name: count, dtype: int64

                                                text                      role
0  SQL PostgreSQL MySQL Query Optimization Data M...        Database Developer
1  Monitoring Linux CI CD Automation Terraform AW...           DevOps Engineer
2  Predictive Modeling Pandas Scikit-learn Featur...            Data Scientist
3  YOLO TensorFlow PyTorch Deep Learning Object D...  Computer Vision Engineer
4  Scikit-learn Deep Learning Machine Learning Te...            AI ML Engineer

In [18]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    career_training_df["text"],
    career_training_df["role"],
    test_size=0.20,
    random_state=42,
    stratify=career_training_df["role"]
)

print("Training samples:", len(X_train))
print("Testing samples:", len(X_test))

Training samples: 960
Testing samples: 240

In [19]:
model = SentenceTransformer(
    "all-MiniLM-L6-v2"
)

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

In [20]:
X_train_embeddings = model.encode(
    X_train.tolist(),
    normalize_embeddings=True,
    show_progress_bar=True
)

X_test_embeddings = model.encode(
    X_test.tolist(),
    normalize_embeddings=True,
    show_progress_bar=True
)

print(
    "Train embedding shape:",
    X_train_embeddings.shape
)

print(
    "Test embedding shape:",
    X_test_embeddings.shape
)

Batches:   0%|          | 0/30 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Train embedding shape: (960, 384)
Test embedding shape: (240, 384)

In [21]:
from sklearn.linear_model import LogisticRegression

career_classifier = LogisticRegression(
    max_iter=2000,
    random_state=42
)

career_classifier.fit(
    X_train_embeddings,
    y_train
)

print(
    "Career classification model trained successfully!"
)

Career classification model trained successfully!

In [22]:
from sklearn.metrics import (
    accuracy_score,
    classification_report
)

y_pred = career_classifier.predict(
    X_test_embeddings
)

accuracy = accuracy_score(
    y_test,
    y_pred
)

print(
    f"Model Accuracy: {accuracy * 100:.2f}%"
)

print("\nClassification Report:\n")

print(
    classification_report(
        y_test,
        y_pred,
        zero_division=0
    )
)

Model Accuracy: 100.00%

Classification Report:

                          precision    recall  f1-score   support

          AI ML Engineer       1.00      1.00      1.00        16
       Backend Developer       1.00      1.00      1.00        16
          Cloud Engineer       1.00      1.00      1.00        16
Computer Vision Engineer       1.00      1.00      1.00        16
   Cybersecurity Analyst       1.00      1.00      1.00        16
            Data Analyst       1.00      1.00      1.00        16
          Data Scientist       1.00      1.00      1.00        16
      Database Developer       1.00      1.00      1.00        16
         DevOps Engineer       1.00      1.00      1.00        16
    Full Stack Developer       1.00      1.00      1.00        16
  Generative AI Engineer       1.00      1.00      1.00        16
          MLOps Engineer       1.00      1.00      1.00        16
            NLP Engineer       1.00      1.00      1.00        16
        Python Developer       1.00      1.00      1.00        16
       Software Engineer       1.00      1.00      1.00        16

                accuracy                           1.00       240
               macro avg       1.00      1.00      1.00       240
            weighted avg       1.00      1.00      1.00       240

In [24]:
def predict_career_ml(
    skills_text,
    top_n=5
):

    embedding = model.encode(
        [skills_text],
        normalize_embeddings=True
    )

    probabilities = (
        career_classifier.predict_proba(
            embedding
        )[0]
    )

    classes = (
        career_classifier.classes_
    )

    results = pd.DataFrame({
        "Career Role": classes,
        "Match Score": probabilities * 100
    })

    results = results.sort_values(
        "Match Score",
        ascending=False
    ).head(top_n)

    return results.reset_index(
        drop=True
    )

In [25]:
predict_career_ml("""
Python
Machine Learning
Deep Learning
Scikit-learn
TensorFlow
FastAPI
Artificial Intelligence
Computer Vision
""")

                Career Role  Match Score
0            AI ML Engineer    50.901309
1  Computer Vision Engineer    19.010079
2            MLOps Engineer     5.605768
3            Data Scientist     4.835963
4              NLP Engineer     3.761614

In [26]:
predict_career_ml("""
React
JavaScript
HTML
CSS
Node.js
Express
MongoDB
REST API
""")

            Career Role  Match Score
0  Full Stack Developer    89.707623
1     Backend Developer     3.678949
2    Database Developer     1.202806
3        Cloud Engineer     0.808885
4       DevOps Engineer     0.715781

In [27]:
predict_career_ml("""
Docker
Kubernetes
Jenkins
AWS
Terraform
Linux
CI CD
""")

            Career Role  Match Score
0       DevOps Engineer    68.411048
1        Cloud Engineer    14.258525
2        MLOps Engineer     6.787059
3  Full Stack Developer     1.699702
4     Backend Developer     1.485519

In [28]:
# =========================
# TEST 1 - AI/ML CANDIDATE
# =========================

print("TEST 1: AI/ML Skills")

ai_result = predict_career_ml("""
Python
Machine Learning
Deep Learning
Scikit-learn
TensorFlow
FastAPI
Artificial Intelligence
Computer Vision
""")

display(ai_result)


# =========================
# TEST 2 - FULL STACK
# =========================

print("\nTEST 2: Full Stack Skills")

fullstack_result = predict_career_ml("""
React
JavaScript
HTML
CSS
Node.js
Express
MongoDB
REST API
""")

display(fullstack_result)


# =========================
# TEST 3 - DEVOPS
# =========================

print("\nTEST 3: DevOps Skills")

devops_result = predict_career_ml("""
Docker
Kubernetes
Jenkins
AWS
Terraform
Linux
CI CD
""")

display(devops_result)

TEST 1: AI/ML Skills

                Career Role  Match Score
0            AI ML Engineer    50.901309
1  Computer Vision Engineer    19.010079
2            MLOps Engineer     5.605768
3            Data Scientist     4.835963
4              NLP Engineer     3.761614

TEST 2: Full Stack Skills

            Career Role  Match Score
0  Full Stack Developer    89.707623
1     Backend Developer     3.678949
2    Database Developer     1.202806
3        Cloud Engineer     0.808885
4       DevOps Engineer     0.715781

TEST 3: DevOps Skills

            Career Role  Match Score
0       DevOps Engineer    68.411048
1        Cloud Engineer    14.258525
2        MLOps Engineer     6.787059
3  Full Stack Developer     1.699702
4     Backend Developer     1.485519

In [29]:
from sklearn.metrics import top_k_accuracy_score
from sklearn.preprocessing import LabelEncoder

# Get prediction probabilities
y_prob = career_classifier.predict_proba(
    X_test_embeddings
)

# Convert role names to numeric labels
label_encoder = LabelEncoder()

label_encoder.fit(
    career_classifier.classes_
)

y_test_encoded = label_encoder.transform(
    y_test
)

top3_accuracy = top_k_accuracy_score(
    y_test_encoded,
    y_prob,
    k=3,
    labels=range(
        len(career_classifier.classes_)
    )
)

print(
    f"Top-3 Accuracy: "
    f"{top3_accuracy * 100:.2f}%"
)

Top-3 Accuracy: 100.00%

In [30]:
def analyze_skill_gap(
    candidate_skills,
    target_role
):

    if target_role not in career_skill_map:

        return {
            "matched_skills": [],
            "missing_skills": [],
            "skill_match_percentage": 0
        }

    required_skills = career_skill_map[
        target_role
    ]

    candidate_text = (
        candidate_skills.lower()
    )

    matched = []

    missing = []

    for skill in required_skills:

        if skill.lower() in candidate_text:

            matched.append(skill)

        else:

            missing.append(skill)

    match_percentage = (
        len(matched)
        / len(required_skills)
    ) * 100

    return {

        "matched_skills":
            matched,

        "missing_skills":
            missing,

        "skill_match_percentage":
            round(match_percentage, 2)
    }

In [31]:
candidate = """

Python
Machine Learning
Scikit-learn
Pandas
NumPy
FastAPI
Artificial Intelligence

"""

gap = analyze_skill_gap(
    candidate,
    "AI ML Engineer"
)

print(
    "Skill Match:",
    gap["skill_match_percentage"],
    "%"
)

print(
    "\nMatched Skills:"
)

print(
    gap["matched_skills"]
)

print(
    "\nMissing Skills:"
)

print(
    gap["missing_skills"]
)

Skill Match: 50.0 %

Matched Skills:
['Python', 'Machine Learning', 'Scikit-learn', 'Pandas', 'NumPy', 'Artificial Intelligence']

Missing Skills:
['Deep Learning', 'TensorFlow', 'PyTorch', 'NLP', 'Computer Vision', 'Model Deployment']

In [32]:
def careerlens_predict(
    candidate_skills,
    top_n=3
):

    # Generate embedding
    embedding = model.encode(
        [candidate_skills],
        normalize_embeddings=True
    )

    # Get probabilities
    probabilities = (
        career_classifier
        .predict_proba(
            embedding
        )[0]
    )

    classes = (
        career_classifier.classes_
    )

    results = pd.DataFrame({

        "Career Role":
            classes,

        "Match Score":
            probabilities * 100
    })

    results = results.sort_values(

        "Match Score",

        ascending=False

    ).head(top_n)

    results = results.reset_index(
        drop=True
    )

    # Best career
    best_role = (
        results.iloc[0][
            "Career Role"
        ]
    )

    confidence = float(
        results.iloc[0][
            "Match Score"
        ]
    )

    # Skill gap
    skill_gap = analyze_skill_gap(
        candidate_skills,
        best_role
    )

    return {

        "best_career":
            best_role,

        "confidence":
            round(confidence, 2),

        "top_careers":
            results,

        "matched_skills":
            skill_gap[
                "matched_skills"
            ],

        "missing_skills":
            skill_gap[
                "missing_skills"
            ],

        "skill_match":
            skill_gap[
                "skill_match_percentage"
            ]
    }

In [33]:
candidate = """

Python
Machine Learning
Scikit-learn
Pandas
NumPy
FastAPI
Generative AI
Gemini
Ollama
React

"""

result = careerlens_predict(
    candidate
)

print(
    "BEST CAREER:",
    result["best_career"]
)

print(
    "MODEL CONFIDENCE:",
    result["confidence"],
    "%"
)

print(
    "SKILL COVERAGE:",
    result["skill_match"],
    "%"
)

print(
    "\nTOP CAREER RECOMMENDATIONS:"
)

display(
    result["top_careers"]
)

print(
    "\nMATCHED SKILLS:"
)

print(
    result["matched_skills"]
)

print(
    "\nSKILLS TO LEARN:"
)

print(
    result["missing_skills"]
)

BEST CAREER: Generative AI Engineer
MODEL CONFIDENCE: 38.16 %
SKILL COVERAGE: 38.46 %

TOP CAREER RECOMMENDATIONS:

              Career Role  Match Score
0  Generative AI Engineer    38.158302
1          AI ML Engineer    20.939464
2          Data Scientist     9.867292

MATCHED SKILLS:
['Python', 'Generative AI', 'Gemini', 'Ollama', 'FastAPI']

SKILLS TO LEARN:
['LLM', 'Prompt Engineering', 'RAG', 'LangChain', 'Vector Databases', 'Embeddings', 'Transformers', 'OpenAI']

In [34]:
# Save classifier
joblib.dump(
    career_classifier,
    "career_classifier.pkl"
)

# Save career skill database
joblib.dump(
    career_skill_map,
    "career_skill_map.pkl"
)

# Save role profiles
joblib.dump(
    career_df,
    "career_profiles.pkl"
)

print(
    "CareerLens AI final model "
    "artifacts saved successfully!"
)

CareerLens AI final model artifacts saved successfully!

In [35]:
import os

files_to_check = [

    "career_classifier.pkl",

    "career_skill_map.pkl",

    "career_profiles.pkl"
]

for file in files_to_check:

    print(
        file,
        "→",
        os.path.getsize(file),
        "bytes"
    )

career_classifier.pkl → 47487 bytes
career_skill_map.pkl → 1747 bytes
career_profiles.pkl → 5815 bytes

In [36]:
from google.colab import files

files.download("career_classifier.pkl")
files.download("career_skill_map.pkl")
files.download("career_profiles.pkl")